version: "2.2"
services:

  # apache/kafka https://hub.docker.com/r/apache/kafka
  kafka:
    container_name: kafka
    image: apache/kafka
    networks:
      - mojo
    ports:
      - "9092:9092/tcp"

  # https://hub.docker.com/r/tekki/mojolicious
  starman:
    container_name: starman
    image: tekki/mojolicious
    ports:
      - "80:80/tcp"
    volumes:
      - ./starman:/starman/
      - ./mojo:/mojo/
    command: >
        bash -c "morbo -v -w my_app/lib/ -l http://*:80 ./my_app/script/my_app"

networks:
  mojo:
