version: "2.2"
services:

  # apache/kafka https://hub.docker.com/r/apache/kafka
#  kafka:
#    container_name: kafka
#    image: apache/kafka
#    networks:
#      - mojo
#    ports:
#      - "9092:9092/tcp"

  # https://hub.docker.com/r/tekki/mojolicious
  starman:
    container_name: starman
    image: tekki/mojolicious
    ports:
      - "80:80/tcp"
    volumes:
      - ./starman:/starman/
      - ./mojo:/mojo/
    command: >
        bash -c "morbo -v -w /mojo/my_app/lib/ -l http://*:80 /mojo/my_app/script/my_app"


  # newman
  newman:
    container_name: newman
    image: ventx/newman-reporter
    volumes:
      - ./newman:/etc/newman/
    entrypoint:
      #run /newman/docker1.postman_collection.json --reporters cli;htmlextra --reporter-htmlextra-export "/newman/rep.html";
      newman run /etc/newman/docker1.postman_collection.json --environment /etc/newman/env.json --reporters cli,htmlextra --reporter-htmlextra-export "/etc/newman/rep.html";
      #sh -c "while true; do sleep 2; done"
      #sh -c "while true; do sleep 2; done"
    # newman run --bail --verbose -e lk.postman_environment.json lk.postman_collection.json

networks:
  mojooff:
